---
services:
  seerr:
    # Request and media discovery manager for Plex/Jellyfin
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    environment:
      # Does not recommend using non-default UID/GID.
      # See the migration documentation and GitHub Issue:
      # https://docs.seerr.dev/migration-guide/?kubernetes-values=old#config-folder-permissions
      # https://github.com/seerr-team/seerr/discussions/2455
      # - PUID=${UID}
      # - PGID=${MEDIACENTER_GID}
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/config/seerr-config:/app/config
    ports:
      - "5055:5055"
    restart: unless-stopped

  tautulli:
    # Monitoring and statistics dashboard for Plex viewing activity
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      # Does not recommend using non-default UID/GID.
      # - PUID=${UID}
      # - PGID=${MEDIACENTER_GID}
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/config/tautulli-config:/config
    ports:
      - "8181:8181"
    restart: unless-stopped

  wizarr:
    # Invite and onboarding manager for Plex/Jellyfin/Emby users
    image: ghcr.io/wizarrrr/wizarr:latest
    container_name: wizarr
    environment:
      # Does not recommend using non-default UID/GID.
      # - PUID=${UID}
      # - PGID=${MEDIACENTER_GID}
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/config/wizarr-config:/data
    ports:
      - "5690:5690"
    restart: unless-stopped
