---
services:
  overseerr:
    # Request and media discovery manager for Plex
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${OVERSEERR_UID}
      - PGID=${MEDIACENTER_GID}
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/config/overseerr-config:/app/config
    ports:
      - "5055:5055"
    restart: unless-stopped

  jellyseerr:
    # Request and media discovery manager for Jellyfin (Overseerr alternative)
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=${JELLYSEERR_UID}
      - PGID=${MEDIACENTER_GID}
      - UMASK=002
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/config/jellyseerr-config:/app/config
    ports:
      - "5056:5055"
    restart: unless-stopped

  tautulli:
    # Monitoring and statistics dashboard for Plex viewing activity
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    # commented out because plex can also run outside of docker
    #depends_on:
    #  - plex
    environment:
      - PUID=${UID}
      - PGID=${MEDIACENTER_GID}
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/config/tautulli-config:/config
    ports:
      - "8181:8181"
    restart: unless-stopped

  wizarr:
    # Invite and onboarding manager for Plex/Jellyfin/Emby users
    image: ghcr.io/wizarrrr/wizarr:latest
    container_name: wizarr
    environment:
      - PUID=${UID}
      - PGID=${MEDIACENTER_GID}
      - TZ=${TIMEZONE}
    volumes:
      - ${ROOT_DIR}/config/wizarr-config:/data
    ports:
      - "5690:5690"
    restart: unless-stopped
